apiVersion: v1
kind: Pod
metadata:
  name: nginx-loadbalancer
  labels:
    app: first-app
    tier: loadbalancer
spec:
  containers:
  - name: nginx-container
    image: nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "256m"
